# Generated by Django 5.0.2 on 2024-03-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gutenberg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunk',
            name='rel_i',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
