# Generated by Django 5.0.2 on 2024-04-08 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gutenberg', '0002_alter_chunk_rel_i'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='raw_book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='gutenberg.rawbook'),
            preserve_default=False,
        ),
    ]
