# Generated by Django 5.0.2 on 2024-04-08 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gutenberg', '0003_chunk_raw_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chunk',
            name='book_gutenberg_id',
        ),
        migrations.RemoveField(
            model_name='chunk',
            name='rel_i',
        ),
    ]
